/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-04-22 09:30:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.MainPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/workspaces/pj/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1743573334378L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- 최성현 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <!-- 메타데이터 및 기본 설정 -->\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"description\" content=\"3부상조 - 당신의 비즈니스 파트너로 차별화된 서비스와 지원을 제공합니다.\">\r\n");
      out.write("    <title>3부상조 - 메인 페이지</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- 구글 웹폰트 로드: Roboto -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- CSS 경로 지정: Header, Footer 스타일 -->\r\n");
      out.write("    <link href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- 페이지 전반적인 CSS 스타일 정의 -->\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("        /* 공통 스타일 초기화 및 글꼴 설정 */\r\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Roboto', sans-serif;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            background-color: #f0f8ff;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 상단 Hero Section 스타일 */\r\n");
      out.write("        .hero-section {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            height: 800px;\r\n");
      out.write("            background: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)),\r\n");
      out.write("                        url('https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80')\r\n");
      out.write("                        no-repeat center center/cover;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            animation: fadeIn 1s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Hero 콘텐츠 박스 */\r\n");
      out.write("        .hero-content {\r\n");
      out.write("            background-color: rgba(255,255,255,0.95);\r\n");
      out.write("            padding: 3rem 4rem;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            box-shadow: 0 6px 12px rgba(0,0,0,0.2);\r\n");
      out.write("            max-width: 700px;\r\n");
      out.write("            animation: slideUp 0.8s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero-content h1 { font-size: 2.5rem; color: #333; margin-bottom: 1rem; }\r\n");
      out.write("        .hero-content p { font-size: 1.2rem; color: #666; margin-bottom: 2rem; }\r\n");
      out.write("\r\n");
      out.write("        /* 버튼 스타일: primary / secondary */\r\n");
      out.write("        .hero-content .btn {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            padding: 0.75rem 1.5rem;\r\n");
      out.write("            background-color: #87ceeb;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            margin: 0.5rem;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .hero-content .btn:hover {\r\n");
      out.write("            background-color: #6ab7d5;\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("        .hero-content .btn.secondary {\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            color: #87ceeb;\r\n");
      out.write("            border: 1px solid #87ceeb;\r\n");
      out.write("        }\r\n");
      out.write("        .hero-content .btn.secondary:hover {\r\n");
      out.write("            background-color: #e0f4ff;\r\n");
      out.write("            color: #6ab7d5;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Features(최근 게시글) 섹션 */\r\n");
      out.write("        .features-section {\r\n");
      out.write("            padding: 4rem 2rem;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .features-section h2 {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        .features-grid {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 2rem;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("        .feature-card {\r\n");
      out.write("            background-color: #f0f8ff;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0,0,0,0.1);\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            width: 300px;\r\n");
      out.write("        }\r\n");
      out.write("        .feature-card:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            box-shadow: 0 6px 12px rgba(0,0,0,0.15);\r\n");
      out.write("        }\r\n");
      out.write("        .feature-card img { width: 60px; height: 60px; margin-bottom: 1rem; }\r\n");
      out.write("        .feature-card h3 { font-size: 1.5rem; color: #333; margin-bottom: 0.5rem; }\r\n");
      out.write("        .feature-card p { font-size: 1rem; color: #666; }\r\n");
      out.write("\r\n");
      out.write("        /* 소식받기 구독 섹션 */\r\n");
      out.write("        .connection-section {\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("            padding: 4rem 2rem;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        .connection-section h2 { font-size: 2rem; margin-bottom: 1rem; }\r\n");
      out.write("        .connection-section p { font-size: 1.2rem; margin-bottom: 2rem; color: #ccc; }\r\n");
      out.write("\r\n");
      out.write("        /* 뉴스레터 입력 폼 스타일 */\r\n");
      out.write("        .newsletter-form {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("        }\r\n");
      out.write("        .newsletter-form input {\r\n");
      out.write("            padding: 0.75rem;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            width: 300px;\r\n");
      out.write("        }\r\n");
      out.write("        .newsletter-form button {\r\n");
      out.write("            padding: 0.75rem 1.5rem;\r\n");
      out.write("            background-color: #87ceeb;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .newsletter-form button:hover {\r\n");
      out.write("            background-color: #6ab7d5;\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 고객 후기 섹션 */\r\n");
      out.write("        .testimonial-section {\r\n");
      out.write("            padding: 4rem 2rem;\r\n");
      out.write("            background-color: #f0f8ff;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .testimonial-section h2 { font-size: 2rem; margin-bottom: 2rem; color: #333; }\r\n");
      out.write("        .testimonial-grid {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 2rem;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("        .testimonial-card {\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0,0,0,0.1);\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            width: 300px;\r\n");
      out.write("        }\r\n");
      out.write("        .testimonial-card:hover { transform: translateY(-5px); }\r\n");
      out.write("        .testimonial-card p {\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            color: #666;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            font-style: italic;\r\n");
      out.write("        }\r\n");
      out.write("        .testimonial-card h4 { font-size: 1.2rem; color: #333; }\r\n");
      out.write("\r\n");
      out.write("        /* 등장 애니메이션 keyframe 정의 */\r\n");
      out.write("        @keyframes fadeIn {\r\n");
      out.write("            from { opacity: 0; }\r\n");
      out.write("            to { opacity: 1; }\r\n");
      out.write("        }\r\n");
      out.write("        @keyframes slideUp {\r\n");
      out.write("            from { transform: translateY(20px); opacity: 0; }\r\n");
      out.write("            to { transform: translateY(0); opacity: 1; }\r\n");
      out.write("        }\r\n");
      out.write("        /* 공통 애니메이션 효과 */\r\n");
      out.write("        .section-animation {\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            transform: translateY(20px);\r\n");
      out.write("            animation: slideUp 0.8s ease-out forwards;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- 페이지 상단 Header: 로고 및 네비게이션 -->\r\n");
      out.write("    <header>\r\n");
      out.write("        <div id=\"logo\"><a href=\"/\">3부상조</a></div>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul class=\"nav-menu\">\r\n");
      out.write("                <li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("                <li><a href=\"login\">로그인</a></li>\r\n");
      out.write("                <li><a href=\"#\">개인정보</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- 메인 배너: Hero Section -->\r\n");
      out.write("    <section class=\"hero-section\">\r\n");
      out.write("        <div class=\"hero-content\">\r\n");
      out.write("            <h1>당신의 성공을 위한 최적의 파트너</h1>\r\n");
      out.write("            <p>3부상조는 차별화된 시스템과 신뢰할 수 있는 서비스로<br>비즈니스 성장을 지원합니다.</p>\r\n");
      out.write("            <a href=\"start\" class=\"btn\">지금 시작하기</a>\r\n");
      out.write("            <a href=\"features\" class=\"btn secondary\">더 알아보기</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- 최근 게시글 소개 영역 -->\r\n");
      out.write("    <section class=\"features-section section-animation\" id=\"features\">\r\n");
      out.write("        <h2>최근 게시글</h2>\r\n");
      out.write("        <div class=\"features-grid\">\r\n");
      out.write("            <!-- 게시글 카드 -->\r\n");
      out.write("            <div class=\"feature-card\">\r\n");
      out.write("                <img src=\"https://via.placeholder.com/60x60?text=아이콘\" alt=\"\">\r\n");
      out.write("                <h3>게시글1</h3>\r\n");
      out.write("                <p>내용</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"feature-card\">\r\n");
      out.write("                <img src=\"https://via.placeholder.com/60x60?text=아이콘\" alt=\"\">\r\n");
      out.write("                <h3>게시글2</h3>\r\n");
      out.write("                <p>내용2</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"feature-card\">\r\n");
      out.write("                <img src=\"https://via.placeholder.com/60x60?text=아이콘\" alt=\"\">\r\n");
      out.write("                <h3>게시글3</h3>\r\n");
      out.write("                <p>내용3</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- 뉴스레터 구독 섹션 -->\r\n");
      out.write("    <section class=\"connection-section section-animation\">\r\n");
      out.write("        <h2>소식받기</h2>\r\n");
      out.write("        <p>뉴스레터를 구독하고 최신 정보를 받아보세요.</p>\r\n");
      out.write("        <div class=\"newsletter-form\">\r\n");
      out.write("            <input type=\"email\" placeholder=\"이메일을 입력하세요\">\r\n");
      out.write("            <button>구독하기</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- 고객 후기 섹션 -->\r\n");
      out.write("    <section class=\"testimonial-section section-animation\">\r\n");
      out.write("        <h2>고객 후기</h2>\r\n");
      out.write("        <div class=\"testimonial-grid\">\r\n");
      out.write("            <div class=\"testimonial-card\">\r\n");
      out.write("                <p>정말 훌륭한 서비스입니다! 믿을 수 있는 비즈니스 파트너.</p>\r\n");
      out.write("                <h4>김철수</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"testimonial-card\">\r\n");
      out.write("                <p>전문적이고 신뢰할 수 있는 고객지원에 만족합니다.</p>\r\n");
      out.write("                <h4>이영희</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"testimonial-card\">\r\n");
      out.write("                <p>3부상조와 함께한 이후 비즈니스가 훨씬 안정적입니다.</p>\r\n");
      out.write("                <h4>박민수</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- 푸터 영역 -->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"footer-content\">\r\n");
      out.write("            <ul class=\"footer-links\">\r\n");
      out.write("                <li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("                <li><a href=\"login\">로그인</a></li>\r\n");
      out.write("                <li><a href=\"#\">개인정보</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"social-icons\">\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p>© 2025 3부삼조. All rights reserved.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/views/MainPage/index.jsp(17,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/resources/css/Header.css");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/views/MainPage/index.jsp(18,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/resources/css/Footer.css");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }
}
