/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-04-22 08:29:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.insa;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chulsuck_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- 최성현 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>3부상조 - 메인 페이지</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("/* Reset default styles */\r\n");
      out.write("* {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    font-family: 'Arial', sans-serif;\r\n");
      out.write("    line-height: 1.6;\r\n");
      out.write("    background-color: #f0f8ff; /* Light sky blue background */\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Header Styles */\r\n");
      out.write("#main-header {\r\n");
      out.write("    background-color: #87ceeb; /* Sky blue theme */\r\n");
      out.write("    padding: 1rem 2rem;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    z-index: 1000;\r\n");
      out.write("    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#logo a {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-size: 1.5rem;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-items {\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    gap: 1.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-items li a {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    padding: 0.5rem 1rem;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-items li a:hover {\r\n");
      out.write("    background-color: #6ab7d5; /* Slightly darker sky blue on hover */\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".badge {\r\n");
      out.write("    background-color: #ff6b6b; /* Coral red for badge */\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    padding: 0.2rem 0.5rem;\r\n");
      out.write("    border-radius: 12px;\r\n");
      out.write("    font-size: 0.8rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Mobile Menu Button */\r\n");
      out.write("#mobile-menu-btn {\r\n");
      out.write("    display: none;\r\n");
      out.write("    background: none;\r\n");
      out.write("    border: none;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mobile-menu-btn span {\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 25px;\r\n");
      out.write("    height: 3px;\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    margin: 5px 0;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Mobile Menu */\r\n");
      out.write("#mobile-menu {\r\n");
      out.write("    display: none;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    right: -250px;\r\n");
      out.write("    width: 250px;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    background-color: #87ceeb; /* Sky blue theme */\r\n");
      out.write("    padding: 5rem 2rem 2rem;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mobile-menu.active {\r\n");
      out.write("    right: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Sidebar (Aside) Styles */\r\n");
      out.write("#sidebar {\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    top: 60px; /* Below the header */\r\n");
      out.write("    left: 0;\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    height: calc(100vh - 60px);\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    border-right: 1px solid #ddd;\r\n");
      out.write("    padding: 1rem;\r\n");
      out.write("    z-index: 999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar nav ul {\r\n");
      out.write("    list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar nav ul li {\r\n");
      out.write("    margin-bottom: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar nav ul li a {\r\n");
      out.write("    color: #333;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("    display: block;\r\n");
      out.write("    padding: 0.5rem;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar nav ul li a:hover {\r\n");
      out.write("    background-color: #e0f4ff; /* Very light sky blue on hover */\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    color: #4682b4; /* Steel blue for text on hover */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Main Content */\r\n");
      out.write("main {\r\n");
      out.write("    margin-top: 60px; /* Space for header */\r\n");
      out.write("    margin-left: 200px; /* Space for sidebar */\r\n");
      out.write("    padding: 2rem;\r\n");
      out.write("    max-width: calc(100% - 200px);\r\n");
      out.write("    min-height: calc(100vh - 60px);\r\n");
      out.write("    background-color: #f0f8ff; /* Match body background */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Attendance Section */\r\n");
      out.write(".attendance-section {\r\n");
      out.write("    max-width: 800px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".attendance-section h1 {\r\n");
      out.write("    font-size: 2rem;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    margin-bottom: 1.5rem;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".date-display {\r\n");
      out.write("    font-size: 1.2rem;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    margin-bottom: 1.5rem;\r\n");
      out.write("    text-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Card Container */\r\n");
      out.write(".card-container {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    gap: 2rem;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    flex-wrap: wrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Attendance Card */\r\n");
      out.write(".attendance-card {\r\n");
      out.write("    background-color: #87ceeb; /* Sky blue theme */\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    padding: 1.5rem;\r\n");
      out.write("    width: 250px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".attendance-card img {\r\n");
      out.write("    width: 100px;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    margin-bottom: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".attendance-card h2 {\r\n");
      out.write("    font-size: 1.5rem;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    margin-bottom: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".attendance-card .time {\r\n");
      out.write("    font-size: 2rem;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    margin-bottom: 0.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".attendance-card .date {\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("    color: #666;\r\n");
      out.write("    margin-bottom: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".attendance-card .btn {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: 0.75rem 1.5rem;\r\n");
      out.write("    background-color: #6ab7d5; /* Slightly darker sky blue */\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("    border: none;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".attendance-card .btn:hover {\r\n");
      out.write("    background-color: #5aa4c2; /* Even darker on hover */\r\n");
      out.write("    transform: translateY(-2px) scale(1.02); /* Lift effect */\r\n");
      out.write("    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); /* Shadow for depth */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive Design */\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("    /* Hide desktop nav and show mobile menu button */\r\n");
      out.write("    .nav-items {\r\n");
      out.write("        display: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #mobile-menu-btn {\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #mobile-menu {\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Hide sidebar on mobile */\r\n");
      out.write("    #sidebar {\r\n");
      out.write("        display: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Adjust main content for mobile */\r\n");
      out.write("    main {\r\n");
      out.write("        margin-left: 0;\r\n");
      out.write("        max-width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .attendance-section h1 {\r\n");
      out.write("        font-size: 1.5rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .date-display {\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .attendance-card {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        max-width: 300px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Additional Styling */\r\n");
      out.write("a {\r\n");
      out.write("    transition: color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover {\r\n");
      out.write("    color: #4682b4; /* Steel blue for links on hover */\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header id=\"main-header\">\r\n");
      out.write("        <div id=\"logo\"><a href=\"/\">3부상조</a></div>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul class=\"nav-items\">\r\n");
      out.write("                <li><a href=\"/\">거래처 등록</a></li>\r\n");
      out.write("                <li><a href=\"/cart\">품목 등록 <span class=\"badge\">0</span></a></li>\r\n");
      out.write("                <li><a href=\"/orders\">재고 조정</a></li>\r\n");
      out.write("                <li><a href=\"/signup\">구매 관리</a></li>\r\n");
      out.write("                <li><a href=\"/login\">판매 관리</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <button id=\"mobile-menu-btn\">\r\n");
      out.write("            <span></span>\r\n");
      out.write("            <span></span>\r\n");
      out.write("            <span></span>\r\n");
      out.write("        </button>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- Mobile Menu -->\r\n");
      out.write("    <aside id=\"mobile-menu\">\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul class=\"nav-items\">\r\n");
      out.write("                <li><a href=\"/\">거래처 등록</a></li>\r\n");
      out.write("                <li><a href=\"/cart\">품목 등록</a></li>\r\n");
      out.write("                <li><a href=\"/orders\">재고 조정</a></li>\r\n");
      out.write("                <li><a href=\"/signup\">구매 관리</a></li>\r\n");
      out.write("                <li><a href=\"/login\">판매 관리</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </aside>\r\n");
      out.write("\r\n");
      out.write("    <!-- Sidebar for Desktop -->\r\n");
      out.write("    <aside id=\"sidebar\">\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"/\">거래처 등록</a></li>\r\n");
      out.write("                <li><a href=\"/cart\">품목 등록</a></li>\r\n");
      out.write("                <li><a href=\"/orders\">재고 조정</a></li>\r\n");
      out.write("                <li><a href=\"/signup\">구매 관리</a></li>\r\n");
      out.write("                <li><a href=\"/login\">판매 관리</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </aside>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main Content -->\r\n");
      out.write("    <main>\r\n");
      out.write("        <section class=\"attendance-section\">\r\n");
      out.write("            <h1>출퇴근 등록</h1>\r\n");
      out.write("            <div class=\"date-display\">< 2025.4.3</div>\r\n");
      out.write("            <div class=\"card-container\">\r\n");
      out.write("                <div class=\"attendance-card\">\r\n");
      out.write("                    <img src=\"https://via.placeholder.com/100x100?text=출근아이콘\" alt=\"출근 아이콘\">\r\n");
      out.write("                    <h2>출근하기</h2>\r\n");
      out.write("                    <div class=\"time\" id=\"checkin-time\">00:00</div>\r\n");
      out.write("                    <div class=\"date\" id=\"checkin-date\">9:00</div>\r\n");
      out.write("                    <button class=\"btn\" onclick=\"recordCheckin()\">출근 등록</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"attendance-card\">\r\n");
      out.write("                    <img src=\"https://via.placeholder.com/100x100?text=퇴근아이콘\" alt=\"퇴근 아이콘\">\r\n");
      out.write("                    <h2>퇴근하기</h2>\r\n");
      out.write("                    <div class=\"time\" id=\"checkout-time\">00:00</div>\r\n");
      out.write("                    <div class=\"date\" id=\"checkout-date\">00:00:00</div>\r\n");
      out.write("                    <button class=\"btn\" onclick=\"recordCheckout()\">퇴근 등록</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        // Format time as HH:MM\r\n");
      out.write("        function formatTime(date) {\r\n");
      out.write("            return date.toTimeString().slice(0, 5);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Format date as YYYY.MM.DD HH:MM:SS\r\n");
      out.write("        function formatDate(date) {\r\n");
      out.write("            return `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${date.getFullYear()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('.');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(date.getMonth() + 1).toString().padStart(2, '0')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('.');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${date.getDate().toString().padStart(2, '0')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${date.toTimeString().slice(0, 8)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Record check-in time\r\n");
      out.write("        function recordCheckin() {\r\n");
      out.write("            const now = new Date();\r\n");
      out.write("            const time = formatTime(now);\r\n");
      out.write("            const date = formatDate(now);\r\n");
      out.write("            \r\n");
      out.write("            // Update display\r\n");
      out.write("            document.getElementById('checkin-time').textContent = time;\r\n");
      out.write("            document.getElementById('checkin-date').textContent = date;\r\n");
      out.write("            \r\n");
      out.write("            // Save to localStorage\r\n");
      out.write("            localStorage.setItem('checkin-time', time);\r\n");
      out.write("            localStorage.setItem('checkin-date', date);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Record check-out time\r\n");
      out.write("        function recordCheckout() {\r\n");
      out.write("            const now = new Date();\r\n");
      out.write("            const time = formatTime(now);\r\n");
      out.write("            const date = formatDate(now);\r\n");
      out.write("            \r\n");
      out.write("            // Update display\r\n");
      out.write("            document.getElementById('checkout-time').textContent = time;\r\n");
      out.write("            document.getElementById('checkout-date').textContent = date;\r\n");
      out.write("            \r\n");
      out.write("            // Save to localStorage\r\n");
      out.write("            localStorage.setItem('checkout-time', time);\r\n");
      out.write("            localStorage.setItem('checkout-date', date);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Load saved times on page load\r\n");
      out.write("        window.onload = function() {\r\n");
      out.write("            const checkinTime = localStorage.getItem('checkin-time');\r\n");
      out.write("            const checkinDate = localStorage.getItem('checkin-date');\r\n");
      out.write("            const checkoutTime = localStorage.getItem('checkout-time');\r\n");
      out.write("            const checkoutDate = localStorage.getItem('checkout-date');\r\n");
      out.write("\r\n");
      out.write("            if (checkinTime && checkinDate) {\r\n");
      out.write("                document.getElementById('checkin-time').textContent = checkinTime;\r\n");
      out.write("                document.getElementById('checkin-date').textContent = checkinDate;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if (checkoutTime && checkoutDate) {\r\n");
      out.write("                document.getElementById('checkout-time').textContent = checkoutTime;\r\n");
      out.write("                document.getElementById('checkout-date').textContent = checkoutDate;\r\n");
      out.write("            }\r\n");
      out.write("        };\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
