/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-04-16 08:58:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Personnel_005fEmployee_005finfor_005finquiry_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>3부상조 - 메인 페이지</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("/* Reset default styles */\r\n");
      out.write("* {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    font-family: 'Arial', sans-serif;\r\n");
      out.write("    line-height: 1.6;\r\n");
      out.write("    background-color: #f0f8ff;\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Header Styles */\r\n");
      out.write("#main-header {\r\n");
      out.write("    background-color: #87ceeb;\r\n");
      out.write("    padding: 1rem 2rem;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    z-index: 1000;\r\n");
      out.write("    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#logo a {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-size: 1.5rem;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-items {\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    gap: 1.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-items li a {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    padding: 0.5rem 1rem;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-items li a:hover {\r\n");
      out.write("    background-color: #6ab7d5;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".badge {\r\n");
      out.write("    background-color: #ff6b6b;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    padding: 0.2rem 0.5rem;\r\n");
      out.write("    border-radius: 12px;\r\n");
      out.write("    font-size: 0.8rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Sidebar (Aside) Styles */\r\n");
      out.write("#sidebar {\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    top: 60px;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    height: calc(100vh - 60px);\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    border-right: 1px solid #ddd;\r\n");
      out.write("    padding: 1rem;\r\n");
      out.write("    z-index: 999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar nav ul {\r\n");
      out.write("    list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar nav ul li {\r\n");
      out.write("    margin-bottom: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar nav ul li a {\r\n");
      out.write("    color: #333;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("    display: block;\r\n");
      out.write("    padding: 0.5rem;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar nav ul li a:hover {\r\n");
      out.write("    background-color: #e0f4ff;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    color: #4682b4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Main Body */\r\n");
      out.write("#main-body {\r\n");
      out.write("    margin-top: 100px;\r\n");
      out.write("    margin-left: 250px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("    margin: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h4 {\r\n");
      out.write("    margin-left: 30px;\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("    margin: 20px 0;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    font-family: sans-serif;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table th, table td {\r\n");
      out.write("    padding: 12px 15px;\r\n");
      out.write("    border: 1px solid #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table thead {\r\n");
      out.write("    background-color: #f2f2f2;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table tbody tr:nth-child(even) {\r\n");
      out.write("    background-color: #f9f9f9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table tbody tr:hover {\r\n");
      out.write("    background-color: #e6f7ff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("    transition: color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover {\r\n");
      out.write("    color: #4682b4;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header id=\"main-header\">\r\n");
      out.write("    <div id=\"logo\"><a href=\"/\">3부상조</a></div>\r\n");
      out.write("    <nav>\r\n");
      out.write("        <ul class=\"nav-items\">\r\n");
      out.write("            <li><a href=\"/\">직원 정보 조회(H)</a></li>\r\n");
      out.write("            <li><a href=\"/cart\">근무 지정</a></li>\r\n");
      out.write("            <li><a href=\"/orders\">인사 관리</a></li>\r\n");
      out.write("            <li><a href=\"/signup\">급여</a></li>\r\n");
      out.write("            <li><a href=\"/login\">휴가</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<aside id=\"sidebar\">\r\n");
      out.write("    <nav>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"/\">직원 정보 조회(L)</a></li>\r\n");
      out.write("            <li><a href=\"/cart\">근무 지정</a></li>\r\n");
      out.write("            <li><a href=\"/orders\">인사 관리</a></li>\r\n");
      out.write("            <li><a href=\"/signup\">급 여</a></li>\r\n");
      out.write("            <li><a href=\"/login\">휴 가</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("</aside>\r\n");
      out.write("\r\n");
      out.write("<div id=\"main-body\">\r\n");
      out.write("    <h2>근무 방식 지정</h2>\r\n");
      out.write("    <h4>설명내용 - 희망 근무지를 선택하세요</h4>\r\n");
      out.write("\r\n");
      out.write("    <div style=\"display: flex; gap: 40px; align-items: flex-start; margin-left: 30px;\">\r\n");
      out.write("        <!-- 지도 영역 -->\r\n");
      out.write("        <div>\r\n");
      out.write("            <p style=\"text-align: center; margin-bottom: 10px;\">지도</p>\r\n");
      out.write("            <img src=\"/resources/images/map.png\" alt=\"지도 이미지\" style=\"width: 200px; height: auto; border: 1px solid #ccc;\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 근무지 선택 영역 -->\r\n");
      out.write("        <form method=\"post\" action=\"/submit-location\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <label for=\"location-select\"><strong>근무지 목록</strong></label><br>\r\n");
      out.write("                <select id=\"location-select\" name=\"location\" size=\"5\" style=\"width: 200px; height: 100px; margin-top: 10px;\">\r\n");
      out.write("                    <option>경기도 연천지부</option>\r\n");
      out.write("                    <option>전라남도 나주지부</option>\r\n");
      out.write("                    <option>경상북도 경산지부</option>\r\n");
      out.write("                    <option>강원도 속초지부</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <br><br>\r\n");
      out.write("\r\n");
      out.write("                <label for=\"detail-address\"><strong>~ 각 지부 별 상세 주소 ~</strong></label><br>\r\n");
      out.write("                <textarea id=\"detail-address\" name=\"detail-address\" rows=\"5\" cols=\"30\" style=\"margin-top: 10px;\"></textarea>\r\n");
      out.write("                <br><br>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\" style=\"padding: 8px 16px;\">신청</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
